// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/quad3d_thetas.fbs".

#pragma once

#include "../datatypes/quad3d_thetas.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Quadrotor actuator angles in radians.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Quad3DThetas {
        rerun::datatypes::Quad3DThetas thetas;

      public:
        Quad3DThetas() = default;

        Quad3DThetas(rerun::datatypes::Quad3DThetas thetas_) : thetas(thetas_) {}

        Quad3DThetas& operator=(rerun::datatypes::Quad3DThetas thetas_) {
            thetas = thetas_;
            return *this;
        }

        /// Cast to the underlying Quad3DThetas datatype
        operator rerun::datatypes::Quad3DThetas() const {
            return thetas;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Quad3DThetas) == sizeof(components::Quad3DThetas));

    /// \private
    template <>
    struct Loggable<components::Quad3DThetas> {
        static constexpr std::string_view ComponentType = "rerun.components.Quad3DThetas";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Quad3DThetas>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Quad3DThetas` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Quad3DThetas* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Quad3DThetas>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Quad3DThetas>::to_arrow(
                    &instances->thetas,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
