// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_magnitude_range.fbs".

#pragma once

#include "../datatypes/trail3d_magnitude_range.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: How a `archetypes::Trail3D` chooses its magnitude range.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DMagnitudeRange {
        rerun::datatypes::Trail3DMagnitudeRange range;

      public:
        Trail3DMagnitudeRange() = default;

        Trail3DMagnitudeRange(rerun::datatypes::Trail3DMagnitudeRange range_) : range(range_) {}

        Trail3DMagnitudeRange& operator=(rerun::datatypes::Trail3DMagnitudeRange range_) {
            range = range_;
            return *this;
        }

        /// Cast to the underlying Trail3DMagnitudeRange datatype
        operator rerun::datatypes::Trail3DMagnitudeRange() const {
            return range;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(
        sizeof(rerun::datatypes::Trail3DMagnitudeRange) == sizeof(components::Trail3DMagnitudeRange)
    );

    /// \private
    template <>
    struct Loggable<components::Trail3DMagnitudeRange> {
        static constexpr std::string_view ComponentType = "rerun.components.Trail3DMagnitudeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Trail3DMagnitudeRange>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Trail3DMagnitudeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Trail3DMagnitudeRange* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Trail3DMagnitudeRange>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Trail3DMagnitudeRange>::to_arrow(
                    &instances->range,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
