// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_color.fbs".

#pragma once

#include "../datatypes/trail3d_color.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: How a `archetypes::Trail3D` chooses its color.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DColor {
        rerun::datatypes::Trail3DColor color;

      public:
        Trail3DColor() = default;

        Trail3DColor(rerun::datatypes::Trail3DColor color_) : color(color_) {}

        Trail3DColor& operator=(rerun::datatypes::Trail3DColor color_) {
            color = color_;
            return *this;
        }

        /// Cast to the underlying Trail3DColor datatype
        operator rerun::datatypes::Trail3DColor() const {
            return color;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Trail3DColor) == sizeof(components::Trail3DColor));

    /// \private
    template <>
    struct Loggable<components::Trail3DColor> {
        static constexpr std::string_view ComponentType = "rerun.components.Trail3DColor";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Trail3DColor>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Trail3DColor` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Trail3DColor* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Trail3DColor>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Trail3DColor>::to_arrow(
                    &instances->color,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
