// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_length.fbs".

#pragma once

#include "../datatypes/trail3d_length.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Trail length for temporal and sequence timelines.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DLength {
        rerun::datatypes::Trail3DLength length;

      public:
        Trail3DLength() = default;

        Trail3DLength(rerun::datatypes::Trail3DLength length_) : length(length_) {}

        Trail3DLength& operator=(rerun::datatypes::Trail3DLength length_) {
            length = length_;
            return *this;
        }

        /// Cast to the underlying Trail3DLength datatype
        operator rerun::datatypes::Trail3DLength() const {
            return length;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Trail3DLength) == sizeof(components::Trail3DLength));

    /// \private
    template <>
    struct Loggable<components::Trail3DLength> {
        static constexpr std::string_view ComponentType = "rerun.components.Trail3DLength";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Trail3DLength>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Trail3DLength` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Trail3DLength* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Trail3DLength>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Trail3DLength>::to_arrow(
                    &instances->length,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
