// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_magnitude.fbs".

#pragma once

#include "../datatypes/float64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: A scalar used to color a `archetypes::Trail3D`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DMagnitude {
        rerun::datatypes::Float64 value;

      public:
        Trail3DMagnitude() = default;

        Trail3DMagnitude(rerun::datatypes::Float64 value_) : value(value_) {}

        Trail3DMagnitude& operator=(rerun::datatypes::Float64 value_) {
            value = value_;
            return *this;
        }

        Trail3DMagnitude(double value_) : value(value_) {}

        Trail3DMagnitude& operator=(double value_) {
            value = value_;
            return *this;
        }

        /// Cast to the underlying Float64 datatype
        operator rerun::datatypes::Float64() const {
            return value;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Float64) == sizeof(components::Trail3DMagnitude));

    /// \private
    template <>
    struct Loggable<components::Trail3DMagnitude> {
        static constexpr std::string_view ComponentType = "rerun.components.Trail3DMagnitude";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Float64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Trail3DMagnitude` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Trail3DMagnitude* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Float64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Float64>::to_arrow(
                    &instances->value,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
