// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_point.fbs".

#pragma once

#include "../datatypes/trail3d_point.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: A 3D point appended to a `archetypes::Trail3D`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DPoint {
        rerun::datatypes::Trail3DPoint point;

      public:
        Trail3DPoint() = default;

        Trail3DPoint(rerun::datatypes::Trail3DPoint point_) : point(point_) {}

        Trail3DPoint& operator=(rerun::datatypes::Trail3DPoint point_) {
            point = point_;
            return *this;
        }

        /// Cast to the underlying Trail3DPoint datatype
        operator rerun::datatypes::Trail3DPoint() const {
            return point;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Trail3DPoint) == sizeof(components::Trail3DPoint));

    /// \private
    template <>
    struct Loggable<components::Trail3DPoint> {
        static constexpr std::string_view ComponentType = "rerun.components.Trail3DPoint";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Trail3DPoint>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::Trail3DPoint` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Trail3DPoint* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Trail3DPoint>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Trail3DPoint>::to_arrow(
                    &instances->point,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
