// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/quad3d_thetas.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Datatype**: Quadrotor actuator angles in radians.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq, bytemuck::Pod, bytemuck::Zeroable)]
#[repr(C)]
pub struct Quad3DThetas {
    /// Front-left actuator angle.
    pub fl: crate::datatypes::Float32,

    /// Front-right actuator angle.
    pub fr: crate::datatypes::Float32,

    /// Rear-left actuator angle.
    pub rl: crate::datatypes::Float32,

    /// Rear-right actuator angle.
    pub rr: crate::datatypes::Float32,
}

::re_types_core::macros::impl_into_cow!(Quad3DThetas);

impl ::re_types_core::Loggable for Quad3DThetas {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new("fl", <crate::datatypes::Float32>::arrow_datatype(), false),
            Field::new("fr", <crate::datatypes::Float32>::arrow_datatype(), false),
            Field::new("rl", <crate::datatypes::Float32>::arrow_datatype(), false),
            Field::new("rr", <crate::datatypes::Float32>::arrow_datatype(), false),
        ]))
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new("fl", <crate::datatypes::Float32>::arrow_datatype(), false),
                Field::new("fr", <crate::datatypes::Float32>::arrow_datatype(), false),
                Field::new("rl", <crate::datatypes::Float32>::arrow_datatype(), false),
                Field::new("rr", <crate::datatypes::Float32>::arrow_datatype(), false),
            ]);
            let (somes, data): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    (datum.is_some(), datum)
                })
                .unzip();
            let validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, fl): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.fl.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let fl_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                fl.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            fl_validity,
                        ))
                    },
                    {
                        let (somes, fr): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.fr.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let fr_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                fr.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            fr_validity,
                        ))
                    },
                    {
                        let (somes, rl): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.rl.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let rl_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                rl.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            rl_validity,
                        ))
                    },
                    {
                        let (somes, rr): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.rr.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let rr_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                rr.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            rr_validity,
                        ))
                    },
                ],
                validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let arrow_data = arrow_data
                .as_any()
                .downcast_ref::<arrow::array::StructArray>()
                .ok_or_else(|| {
                    let expected = Self::arrow_datatype();
                    let actual = arrow_data.data_type().clone();
                    DeserializationError::datatype_mismatch(expected, actual)
                })
                .with_context("rerun.datatypes.Quad3DThetas")?;
            if arrow_data.is_empty() {
                Vec::new()
            } else {
                let (arrow_data_fields, arrow_data_arrays) =
                    (arrow_data.fields(), arrow_data.columns());
                let arrays_by_name: ::std::collections::HashMap<_, _> = arrow_data_fields
                    .iter()
                    .map(|field| field.name().as_str())
                    .zip(arrow_data_arrays)
                    .collect();
                let fl = {
                    if !arrays_by_name.contains_key("fl") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "fl",
                        ))
                        .with_context("rerun.datatypes.Quad3DThetas");
                    }
                    let arrow_data = &**arrays_by_name["fl"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Quad3DThetas#fl")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                let fr = {
                    if !arrays_by_name.contains_key("fr") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "fr",
                        ))
                        .with_context("rerun.datatypes.Quad3DThetas");
                    }
                    let arrow_data = &**arrays_by_name["fr"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Quad3DThetas#fr")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                let rl = {
                    if !arrays_by_name.contains_key("rl") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "rl",
                        ))
                        .with_context("rerun.datatypes.Quad3DThetas");
                    }
                    let arrow_data = &**arrays_by_name["rl"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Quad3DThetas#rl")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                let rr = {
                    if !arrays_by_name.contains_key("rr") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "rr",
                        ))
                        .with_context("rerun.datatypes.Quad3DThetas");
                    }
                    let arrow_data = &**arrays_by_name["rr"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Quad3DThetas#rr")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                ZipValidity::new_with_validity(
                    ::itertools::izip!(fl, fr, rl, rr),
                    arrow_data.nulls(),
                )
                .map(|opt| {
                    opt.map(|(fl, fr, rl, rr)| {
                        Ok(Self {
                            fl: fl
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Quad3DThetas#fl")?,
                            fr: fr
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Quad3DThetas#fr")?,
                            rl: rl
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Quad3DThetas#rl")?,
                            rr: rr
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Quad3DThetas#rr")?,
                        })
                    })
                    .transpose()
                })
                .collect::<DeserializationResult<Vec<_>>>()
                .with_context("rerun.datatypes.Quad3DThetas")?
            }
        })
    }
}

impl ::re_byte_size::SizeBytes for Quad3DThetas {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.fl.heap_size_bytes()
            + self.fr.heap_size_bytes()
            + self.rl.heap_size_bytes()
            + self.rr.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::Float32>::is_pod()
            && <crate::datatypes::Float32>::is_pod()
            && <crate::datatypes::Float32>::is_pod()
            && <crate::datatypes::Float32>::is_pod()
    }
}
