// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_point.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Datatype**: A point in 3D space used by [`archetypes::Trail3D`][crate::archetypes::Trail3D].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq, bytemuck::Pod, bytemuck::Zeroable)]
#[repr(C)]
pub struct Trail3DPoint {
    /// X coordinate.
    pub x: crate::datatypes::Float32,

    /// Y coordinate.
    pub y: crate::datatypes::Float32,

    /// Z coordinate.
    pub z: crate::datatypes::Float32,
}

::re_types_core::macros::impl_into_cow!(Trail3DPoint);

impl ::re_types_core::Loggable for Trail3DPoint {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new("x", <crate::datatypes::Float32>::arrow_datatype(), false),
            Field::new("y", <crate::datatypes::Float32>::arrow_datatype(), false),
            Field::new("z", <crate::datatypes::Float32>::arrow_datatype(), false),
        ]))
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new("x", <crate::datatypes::Float32>::arrow_datatype(), false),
                Field::new("y", <crate::datatypes::Float32>::arrow_datatype(), false),
                Field::new("z", <crate::datatypes::Float32>::arrow_datatype(), false),
            ]);
            let (somes, data): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    (datum.is_some(), datum)
                })
                .unzip();
            let validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, x): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.x.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let x_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                x.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            x_validity,
                        ))
                    },
                    {
                        let (somes, y): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.y.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let y_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                y.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            y_validity,
                        ))
                    },
                    {
                        let (somes, z): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.z.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let z_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float32Type>::new(
                            ScalarBuffer::from(
                                z.into_iter()
                                    .map(|datum| datum.map(|datum| datum.0).unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            z_validity,
                        ))
                    },
                ],
                validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let arrow_data = arrow_data
                .as_any()
                .downcast_ref::<arrow::array::StructArray>()
                .ok_or_else(|| {
                    let expected = Self::arrow_datatype();
                    let actual = arrow_data.data_type().clone();
                    DeserializationError::datatype_mismatch(expected, actual)
                })
                .with_context("rerun.datatypes.Trail3DPoint")?;
            if arrow_data.is_empty() {
                Vec::new()
            } else {
                let (arrow_data_fields, arrow_data_arrays) =
                    (arrow_data.fields(), arrow_data.columns());
                let arrays_by_name: ::std::collections::HashMap<_, _> = arrow_data_fields
                    .iter()
                    .map(|field| field.name().as_str())
                    .zip(arrow_data_arrays)
                    .collect();
                let x = {
                    if !arrays_by_name.contains_key("x") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "x",
                        ))
                        .with_context("rerun.datatypes.Trail3DPoint");
                    }
                    let arrow_data = &**arrays_by_name["x"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DPoint#x")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                let y = {
                    if !arrays_by_name.contains_key("y") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "y",
                        ))
                        .with_context("rerun.datatypes.Trail3DPoint");
                    }
                    let arrow_data = &**arrays_by_name["y"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DPoint#y")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                let z = {
                    if !arrays_by_name.contains_key("z") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "z",
                        ))
                        .with_context("rerun.datatypes.Trail3DPoint");
                    }
                    let arrow_data = &**arrays_by_name["z"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float32Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float32;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DPoint#z")?
                        .into_iter()
                        .map(|res_or_opt| res_or_opt.map(crate::datatypes::Float32))
                };
                ZipValidity::new_with_validity(::itertools::izip!(x, y, z), arrow_data.nulls())
                    .map(|opt| {
                        opt.map(|(x, y, z)| {
                            Ok(Self {
                                x: x.ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.datatypes.Trail3DPoint#x")?,
                                y: y.ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.datatypes.Trail3DPoint#y")?,
                                z: z.ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.datatypes.Trail3DPoint#z")?,
                            })
                        })
                        .transpose()
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.datatypes.Trail3DPoint")?
            }
        })
    }
}

impl ::re_byte_size::SizeBytes for Trail3DPoint {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.x.heap_size_bytes() + self.y.heap_size_bytes() + self.z.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::Float32>::is_pod()
            && <crate::datatypes::Float32>::is_pod()
            && <crate::datatypes::Float32>::is_pod()
    }
}
