// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_magnitude_range.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Datatype**: Magnitude range selection for a [`archetypes::Trail3D`][crate::archetypes::Trail3D].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq)]
#[repr(C)]
pub struct Trail3DMagnitudeRange {
    /// 1 means auto, 2 means fixed.
    pub mode: u8,

    /// Fixed range minimum.
    pub min: f64,

    /// Fixed range maximum.
    pub max: f64,
}

::re_types_core::macros::impl_into_cow!(Trail3DMagnitudeRange);

impl ::re_types_core::Loggable for Trail3DMagnitudeRange {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new("mode", DataType::UInt8, false),
            Field::new("min", DataType::Float64, false),
            Field::new("max", DataType::Float64, false),
        ]))
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new("mode", DataType::UInt8, false),
                Field::new("min", DataType::Float64, false),
                Field::new("max", DataType::Float64, false),
            ]);
            let (somes, data): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    (datum.is_some(), datum)
                })
                .unzip();
            let validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, mode): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.mode.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let mode_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<UInt8Type>::new(
                            ScalarBuffer::from(
                                mode.into_iter()
                                    .map(|v| v.unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            mode_validity,
                        ))
                    },
                    {
                        let (somes, min): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.min.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let min_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float64Type>::new(
                            ScalarBuffer::from(
                                min.into_iter()
                                    .map(|v| v.unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            min_validity,
                        ))
                    },
                    {
                        let (somes, max): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = datum.as_ref().map(|datum| datum.max.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let max_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<Float64Type>::new(
                            ScalarBuffer::from(
                                max.into_iter()
                                    .map(|v| v.unwrap_or_default())
                                    .collect::<Vec<_>>(),
                            ),
                            max_validity,
                        ))
                    },
                ],
                validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let arrow_data = arrow_data
                .as_any()
                .downcast_ref::<arrow::array::StructArray>()
                .ok_or_else(|| {
                    let expected = Self::arrow_datatype();
                    let actual = arrow_data.data_type().clone();
                    DeserializationError::datatype_mismatch(expected, actual)
                })
                .with_context("rerun.datatypes.Trail3DMagnitudeRange")?;
            if arrow_data.is_empty() {
                Vec::new()
            } else {
                let (arrow_data_fields, arrow_data_arrays) =
                    (arrow_data.fields(), arrow_data.columns());
                let arrays_by_name: ::std::collections::HashMap<_, _> = arrow_data_fields
                    .iter()
                    .map(|field| field.name().as_str())
                    .zip(arrow_data_arrays)
                    .collect();
                let mode = {
                    if !arrays_by_name.contains_key("mode") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "mode",
                        ))
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange");
                    }
                    let arrow_data = &**arrays_by_name["mode"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<UInt8Array>()
                        .ok_or_else(|| {
                            let expected = DataType::UInt8;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange#mode")?
                        .into_iter()
                };
                let min = {
                    if !arrays_by_name.contains_key("min") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "min",
                        ))
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange");
                    }
                    let arrow_data = &**arrays_by_name["min"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float64Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float64;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange#min")?
                        .into_iter()
                };
                let max = {
                    if !arrays_by_name.contains_key("max") {
                        return Err(DeserializationError::missing_struct_field(
                            Self::arrow_datatype(),
                            "max",
                        ))
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange");
                    }
                    let arrow_data = &**arrays_by_name["max"];
                    arrow_data
                        .as_any()
                        .downcast_ref::<Float64Array>()
                        .ok_or_else(|| {
                            let expected = DataType::Float64;
                            let actual = arrow_data.data_type().clone();
                            DeserializationError::datatype_mismatch(expected, actual)
                        })
                        .with_context("rerun.datatypes.Trail3DMagnitudeRange#max")?
                        .into_iter()
                };
                ZipValidity::new_with_validity(
                    ::itertools::izip!(mode, min, max),
                    arrow_data.nulls(),
                )
                .map(|opt| {
                    opt.map(|(mode, min, max)| {
                        Ok(Self {
                            mode: mode
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Trail3DMagnitudeRange#mode")?,
                            min: min
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Trail3DMagnitudeRange#min")?,
                            max: max
                                .ok_or_else(DeserializationError::missing_data)
                                .with_context("rerun.datatypes.Trail3DMagnitudeRange#max")?,
                        })
                    })
                    .transpose()
                })
                .collect::<DeserializationResult<Vec<_>>>()
                .with_context("rerun.datatypes.Trail3DMagnitudeRange")?
            }
        })
    }
}

impl ::re_byte_size::SizeBytes for Trail3DMagnitudeRange {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.mode.heap_size_bytes() + self.min.heap_size_bytes() + self.max.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <u8>::is_pod() && <f64>::is_pod() && <f64>::is_pod()
    }
}
