// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_length.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Trail length for temporal and sequence timelines.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, Copy, PartialEq)]
#[repr(transparent)]
pub struct Trail3DLength(pub crate::datatypes::Trail3DLength);

impl ::re_types_core::WrapperComponent for Trail3DLength {
    type Datatype = crate::datatypes::Trail3DLength;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.Trail3DLength".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(Trail3DLength);

impl<T: Into<crate::datatypes::Trail3DLength>> From<T> for Trail3DLength {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::Trail3DLength> for Trail3DLength {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::Trail3DLength {
        &self.0
    }
}

impl std::ops::Deref for Trail3DLength {
    type Target = crate::datatypes::Trail3DLength;

    #[inline]
    fn deref(&self) -> &crate::datatypes::Trail3DLength {
        &self.0
    }
}

impl std::ops::DerefMut for Trail3DLength {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::Trail3DLength {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for Trail3DLength {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::Trail3DLength>::is_pod()
    }
}
