// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/quad3d.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/quad3d_model.hpp"
#include "../components/quad3d_thetas.hpp"
#include "../components/show_labels.hpp"
#include "../components/text.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A quadrotor model rendered from local GLB assets.
    ///
    /// The quadrotor pose is logged through normal `archetypes::Transform3D`
    /// translation/quaternion components by the Rust extension constructor.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Quad3D {
        /// Quadrotor actuator angles in radians.
        std::optional<ComponentBatch> thetas;

        /// The GLB model filename.
        std::optional<ComponentBatch> model;

        /// Optional text label for the quadrotor.
        std::optional<ComponentBatch> label;

        /// Whether the text label should be shown.
        std::optional<ComponentBatch> show_label;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.Quad3D";

        /// `ComponentDescriptor` for the `thetas` field.
        static constexpr auto Descriptor_thetas = ComponentDescriptor(
            ArchetypeName, "Quad3D:thetas", Loggable<rerun::components::Quad3DThetas>::ComponentType
        );
        /// `ComponentDescriptor` for the `model` field.
        static constexpr auto Descriptor_model = ComponentDescriptor(
            ArchetypeName, "Quad3D:model", Loggable<rerun::components::Quad3DModel>::ComponentType
        );
        /// `ComponentDescriptor` for the `label` field.
        static constexpr auto Descriptor_label = ComponentDescriptor(
            ArchetypeName, "Quad3D:label", Loggable<rerun::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `show_label` field.
        static constexpr auto Descriptor_show_label = ComponentDescriptor(
            ArchetypeName, "Quad3D:show_label",
            Loggable<rerun::components::ShowLabels>::ComponentType
        );

      public:
        Quad3D() = default;
        Quad3D(Quad3D&& other) = default;
        Quad3D(const Quad3D& other) = default;
        Quad3D& operator=(const Quad3D& other) = default;
        Quad3D& operator=(Quad3D&& other) = default;

        explicit Quad3D(rerun::components::Quad3DThetas _thetas)
            : thetas(
                  ComponentBatch::from_loggable(std::move(_thetas), Descriptor_thetas)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `Quad3D`.
        static Quad3D update_fields() {
            return Quad3D();
        }

        /// Clear all the fields of a `Quad3D`.
        static Quad3D clear_fields();

        /// Quadrotor actuator angles in radians.
        Quad3D with_thetas(const rerun::components::Quad3DThetas& _thetas) && {
            thetas = ComponentBatch::from_loggable(_thetas, Descriptor_thetas).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `thetas` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_thetas` should
        /// be used when logging a single row's worth of data.
        Quad3D with_many_thetas(const Collection<rerun::components::Quad3DThetas>& _thetas) && {
            thetas = ComponentBatch::from_loggable(_thetas, Descriptor_thetas).value_or_throw();
            return std::move(*this);
        }

        /// The GLB model filename.
        Quad3D with_model(const rerun::components::Quad3DModel& _model) && {
            model = ComponentBatch::from_loggable(_model, Descriptor_model).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `model` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_model` should
        /// be used when logging a single row's worth of data.
        Quad3D with_many_model(const Collection<rerun::components::Quad3DModel>& _model) && {
            model = ComponentBatch::from_loggable(_model, Descriptor_model).value_or_throw();
            return std::move(*this);
        }

        /// Optional text label for the quadrotor.
        Quad3D with_label(const rerun::components::Text& _label) && {
            label = ComponentBatch::from_loggable(_label, Descriptor_label).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `label` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_label` should
        /// be used when logging a single row's worth of data.
        Quad3D with_many_label(const Collection<rerun::components::Text>& _label) && {
            label = ComponentBatch::from_loggable(_label, Descriptor_label).value_or_throw();
            return std::move(*this);
        }

        /// Whether the text label should be shown.
        Quad3D with_show_label(const rerun::components::ShowLabels& _show_label) && {
            show_label =
                ComponentBatch::from_loggable(_show_label, Descriptor_show_label).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `show_label` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_show_label` should
        /// be used when logging a single row's worth of data.
        Quad3D with_many_show_label(
            const Collection<rerun::components::ShowLabels>& _show_label
        ) && {
            show_label =
                ComponentBatch::from_loggable(_show_label, Descriptor_show_label).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::Quad3D> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::Quad3D& archetype);
    };
} // namespace rerun
