// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/quad3d.fbs".

#include "quad3d.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    Quad3D Quad3D::clear_fields() {
        auto archetype = Quad3D();
        archetype.thetas = ComponentBatch::empty<rerun::components::Quad3DThetas>(Descriptor_thetas)
                               .value_or_throw();
        archetype.model = ComponentBatch::empty<rerun::components::Quad3DModel>(Descriptor_model)
                              .value_or_throw();
        archetype.label =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_label).value_or_throw();
        archetype.show_label =
            ComponentBatch::empty<rerun::components::ShowLabels>(Descriptor_show_label)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> Quad3D::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(4);
        if (thetas.has_value()) {
            columns.push_back(thetas.value().partitioned(lengths_).value_or_throw());
        }
        if (model.has_value()) {
            columns.push_back(model.value().partitioned(lengths_).value_or_throw());
        }
        if (label.has_value()) {
            columns.push_back(label.value().partitioned(lengths_).value_or_throw());
        }
        if (show_label.has_value()) {
            columns.push_back(show_label.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> Quad3D::columns() {
        if (thetas.has_value()) {
            return columns(std::vector<uint32_t>(thetas.value().length(), 1));
        }
        if (model.has_value()) {
            return columns(std::vector<uint32_t>(model.value().length(), 1));
        }
        if (label.has_value()) {
            return columns(std::vector<uint32_t>(label.value().length(), 1));
        }
        if (show_label.has_value()) {
            return columns(std::vector<uint32_t>(show_label.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::Quad3D>::as_batches(
        const archetypes::Quad3D& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(4);

        if (archetype.thetas.has_value()) {
            cells.push_back(archetype.thetas.value());
        }
        if (archetype.model.has_value()) {
            cells.push_back(archetype.model.value());
        }
        if (archetype.label.has_value()) {
            cells.push_back(archetype.label.value());
        }
        if (archetype.show_label.has_value()) {
            cells.push_back(archetype.show_label.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
