// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/trail3d.fbs".

#include "trail3d.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    Trail3D Trail3D::clear_fields() {
        auto archetype = Trail3D();
        archetype.point = ComponentBatch::empty<rerun::components::Trail3DPoint>(Descriptor_point)
                              .value_or_throw();
        archetype.color = ComponentBatch::empty<rerun::components::Trail3DColor>(Descriptor_color)
                              .value_or_throw();
        archetype.radius =
            ComponentBatch::empty<rerun::components::Radius>(Descriptor_radius).value_or_throw();
        archetype.length =
            ComponentBatch::empty<rerun::components::Trail3DLength>(Descriptor_length)
                .value_or_throw();
        archetype.magnitude =
            ComponentBatch::empty<rerun::components::Trail3DMagnitude>(Descriptor_magnitude)
                .value_or_throw();
        archetype.magnitude_range = ComponentBatch::empty<rerun::components::Trail3DMagnitudeRange>(
                                        Descriptor_magnitude_range
        )
                                        .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> Trail3D::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(6);
        if (point.has_value()) {
            columns.push_back(point.value().partitioned(lengths_).value_or_throw());
        }
        if (color.has_value()) {
            columns.push_back(color.value().partitioned(lengths_).value_or_throw());
        }
        if (radius.has_value()) {
            columns.push_back(radius.value().partitioned(lengths_).value_or_throw());
        }
        if (length.has_value()) {
            columns.push_back(length.value().partitioned(lengths_).value_or_throw());
        }
        if (magnitude.has_value()) {
            columns.push_back(magnitude.value().partitioned(lengths_).value_or_throw());
        }
        if (magnitude_range.has_value()) {
            columns.push_back(magnitude_range.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> Trail3D::columns() {
        if (point.has_value()) {
            return columns(std::vector<uint32_t>(point.value().length(), 1));
        }
        if (color.has_value()) {
            return columns(std::vector<uint32_t>(color.value().length(), 1));
        }
        if (radius.has_value()) {
            return columns(std::vector<uint32_t>(radius.value().length(), 1));
        }
        if (length.has_value()) {
            return columns(std::vector<uint32_t>(length.value().length(), 1));
        }
        if (magnitude.has_value()) {
            return columns(std::vector<uint32_t>(magnitude.value().length(), 1));
        }
        if (magnitude_range.has_value()) {
            return columns(std::vector<uint32_t>(magnitude_range.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::Trail3D>::as_batches(
        const archetypes::Trail3D& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(6);

        if (archetype.point.has_value()) {
            cells.push_back(archetype.point.value());
        }
        if (archetype.color.has_value()) {
            cells.push_back(archetype.color.value());
        }
        if (archetype.radius.has_value()) {
            cells.push_back(archetype.radius.value());
        }
        if (archetype.length.has_value()) {
            cells.push_back(archetype.length.value());
        }
        if (archetype.magnitude.has_value()) {
            cells.push_back(archetype.magnitude.value());
        }
        if (archetype.magnitude_range.has_value()) {
            cells.push_back(archetype.magnitude_range.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
