// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/trail3d.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/radius.hpp"
#include "../components/trail3d_color.hpp"
#include "../components/trail3d_length.hpp"
#include "../components/trail3d_magnitude.hpp"
#include "../components/trail3d_magnitude_range.hpp"
#include "../components/trail3d_point.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A time-windowed 3D trail built from logged points.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3D {
        /// A 3D point appended to the trail.
        std::optional<ComponentBatch> point;

        /// How the trail color is chosen.
        std::optional<ComponentBatch> color;

        /// The rendered trail line radius.
        std::optional<ComponentBatch> radius;

        /// Trail length for temporal and sequence timelines.
        std::optional<ComponentBatch> length;

        /// Optional scalar used to color the trail.
        std::optional<ComponentBatch> magnitude;

        /// How the magnitude range is chosen.
        std::optional<ComponentBatch> magnitude_range;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.Trail3D";

        /// `ComponentDescriptor` for the `point` field.
        static constexpr auto Descriptor_point = ComponentDescriptor(
            ArchetypeName, "Trail3D:point", Loggable<rerun::components::Trail3DPoint>::ComponentType
        );
        /// `ComponentDescriptor` for the `color` field.
        static constexpr auto Descriptor_color = ComponentDescriptor(
            ArchetypeName, "Trail3D:color", Loggable<rerun::components::Trail3DColor>::ComponentType
        );
        /// `ComponentDescriptor` for the `radius` field.
        static constexpr auto Descriptor_radius = ComponentDescriptor(
            ArchetypeName, "Trail3D:radius", Loggable<rerun::components::Radius>::ComponentType
        );
        /// `ComponentDescriptor` for the `length` field.
        static constexpr auto Descriptor_length = ComponentDescriptor(
            ArchetypeName, "Trail3D:length",
            Loggable<rerun::components::Trail3DLength>::ComponentType
        );
        /// `ComponentDescriptor` for the `magnitude` field.
        static constexpr auto Descriptor_magnitude = ComponentDescriptor(
            ArchetypeName, "Trail3D:magnitude",
            Loggable<rerun::components::Trail3DMagnitude>::ComponentType
        );
        /// `ComponentDescriptor` for the `magnitude_range` field.
        static constexpr auto Descriptor_magnitude_range = ComponentDescriptor(
            ArchetypeName, "Trail3D:magnitude_range",
            Loggable<rerun::components::Trail3DMagnitudeRange>::ComponentType
        );

      public:
        Trail3D() = default;
        Trail3D(Trail3D&& other) = default;
        Trail3D(const Trail3D& other) = default;
        Trail3D& operator=(const Trail3D& other) = default;
        Trail3D& operator=(Trail3D&& other) = default;

        explicit Trail3D(rerun::components::Trail3DPoint _point)
            : point(
                  ComponentBatch::from_loggable(std::move(_point), Descriptor_point)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `Trail3D`.
        static Trail3D update_fields() {
            return Trail3D();
        }

        /// Clear all the fields of a `Trail3D`.
        static Trail3D clear_fields();

        /// A 3D point appended to the trail.
        Trail3D with_point(const rerun::components::Trail3DPoint& _point) && {
            point = ComponentBatch::from_loggable(_point, Descriptor_point).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `point` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_point` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_point(const Collection<rerun::components::Trail3DPoint>& _point) && {
            point = ComponentBatch::from_loggable(_point, Descriptor_point).value_or_throw();
            return std::move(*this);
        }

        /// How the trail color is chosen.
        Trail3D with_color(const rerun::components::Trail3DColor& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `color` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_color` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_color(const Collection<rerun::components::Trail3DColor>& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// The rendered trail line radius.
        Trail3D with_radius(const rerun::components::Radius& _radius) && {
            radius = ComponentBatch::from_loggable(_radius, Descriptor_radius).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `radius` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_radius` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_radius(const Collection<rerun::components::Radius>& _radius) && {
            radius = ComponentBatch::from_loggable(_radius, Descriptor_radius).value_or_throw();
            return std::move(*this);
        }

        /// Trail length for temporal and sequence timelines.
        Trail3D with_length(const rerun::components::Trail3DLength& _length) && {
            length = ComponentBatch::from_loggable(_length, Descriptor_length).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `length` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_length` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_length(const Collection<rerun::components::Trail3DLength>& _length) && {
            length = ComponentBatch::from_loggable(_length, Descriptor_length).value_or_throw();
            return std::move(*this);
        }

        /// Optional scalar used to color the trail.
        Trail3D with_magnitude(const rerun::components::Trail3DMagnitude& _magnitude) && {
            magnitude =
                ComponentBatch::from_loggable(_magnitude, Descriptor_magnitude).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `magnitude` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_magnitude` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_magnitude(
            const Collection<rerun::components::Trail3DMagnitude>& _magnitude
        ) && {
            magnitude =
                ComponentBatch::from_loggable(_magnitude, Descriptor_magnitude).value_or_throw();
            return std::move(*this);
        }

        /// How the magnitude range is chosen.
        Trail3D with_magnitude_range(
            const rerun::components::Trail3DMagnitudeRange& _magnitude_range
        ) && {
            magnitude_range =
                ComponentBatch::from_loggable(_magnitude_range, Descriptor_magnitude_range)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `magnitude_range` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_magnitude_range` should
        /// be used when logging a single row's worth of data.
        Trail3D with_many_magnitude_range(
            const Collection<rerun::components::Trail3DMagnitudeRange>& _magnitude_range
        ) && {
            magnitude_range =
                ComponentBatch::from_loggable(_magnitude_range, Descriptor_magnitude_range)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::Trail3D> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::Trail3D& archetype);
    };
} // namespace rerun
