# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/quad3d_model.fbs".

# You can extend this class by creating a "Quad3DModelExt" class in "quad3d_model_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Quad3DModel", "Quad3DModelBatch"]


class Quad3DModel(datatypes.Utf8, ComponentMixin):
    """
    **Component**: The GLB model filename used by [`archetypes.Quad3D`][rerun.archetypes.Quad3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Quad3DModelExt in quad3d_model_ext.py

    # Note: there are no fields here because Quad3DModel delegates to datatypes.Utf8


class Quad3DModelBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Quad3DModel"


# This is patched in late to avoid circular dependencies.
Quad3DModel._BATCH_TYPE = Quad3DModelBatch  # type: ignore[assignment]
