# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/quad3d_thetas.fbs".

# You can extend this class by creating a "Quad3DThetasExt" class in "quad3d_thetas_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Quad3DThetas", "Quad3DThetasBatch"]


class Quad3DThetas(datatypes.Quad3DThetas, ComponentMixin):
    """
    **Component**: Quadrotor actuator angles in radians.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Quad3DThetasExt in quad3d_thetas_ext.py

    # Note: there are no fields here because Quad3DThetas delegates to datatypes.Quad3DThetas


class Quad3DThetasBatch(datatypes.Quad3DThetasBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Quad3DThetas"


# This is patched in late to avoid circular dependencies.
Quad3DThetas._BATCH_TYPE = Quad3DThetasBatch  # type: ignore[assignment]
