# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_magnitude.fbs".

# You can extend this class by creating a "Trail3DMagnitudeExt" class in "trail3d_magnitude_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Trail3DMagnitude", "Trail3DMagnitudeBatch"]


class Trail3DMagnitude(datatypes.Float64, ComponentMixin):
    """
    **Component**: A scalar used to color a [`archetypes.Trail3D`][rerun.archetypes.Trail3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Trail3DMagnitudeExt in trail3d_magnitude_ext.py

    # Note: there are no fields here because Trail3DMagnitude delegates to datatypes.Float64


class Trail3DMagnitudeBatch(datatypes.Float64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Trail3DMagnitude"


# This is patched in late to avoid circular dependencies.
Trail3DMagnitude._BATCH_TYPE = Trail3DMagnitudeBatch  # type: ignore[assignment]
