# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_length.fbs".

# You can extend this class by creating a "Trail3DLengthExt" class in "trail3d_length_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Trail3DLength", "Trail3DLengthBatch"]


class Trail3DLength(datatypes.Trail3DLength, ComponentMixin):
    """
    **Component**: Trail length for temporal and sequence timelines.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Trail3DLengthExt in trail3d_length_ext.py

    # Note: there are no fields here because Trail3DLength delegates to datatypes.Trail3DLength


class Trail3DLengthBatch(datatypes.Trail3DLengthBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Trail3DLength"


# This is patched in late to avoid circular dependencies.
Trail3DLength._BATCH_TYPE = Trail3DLengthBatch  # type: ignore[assignment]
