# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_point.fbs".

# You can extend this class by creating a "Trail3DPointExt" class in "trail3d_point_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Trail3DPoint", "Trail3DPointBatch"]


class Trail3DPoint(datatypes.Trail3DPoint, ComponentMixin):
    """
    **Component**: A 3D point appended to a [`archetypes.Trail3D`][rerun.archetypes.Trail3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Trail3DPointExt in trail3d_point_ext.py

    # Note: there are no fields here because Trail3DPoint delegates to datatypes.Trail3DPoint


class Trail3DPointBatch(datatypes.Trail3DPointBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Trail3DPoint"


# This is patched in late to avoid circular dependencies.
Trail3DPoint._BATCH_TYPE = Trail3DPointBatch  # type: ignore[assignment]
