# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_magnitude_range.fbs".

# You can extend this class by creating a "Trail3DMagnitudeRangeExt" class in "trail3d_magnitude_range_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Trail3DMagnitudeRange", "Trail3DMagnitudeRangeBatch"]


class Trail3DMagnitudeRange(datatypes.Trail3DMagnitudeRange, ComponentMixin):
    """
    **Component**: How a [`archetypes.Trail3D`][rerun.archetypes.Trail3D] chooses its magnitude range.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Trail3DMagnitudeRangeExt in trail3d_magnitude_range_ext.py

    # Note: there are no fields here because Trail3DMagnitudeRange delegates to datatypes.Trail3DMagnitudeRange


class Trail3DMagnitudeRangeBatch(datatypes.Trail3DMagnitudeRangeBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Trail3DMagnitudeRange"


# This is patched in late to avoid circular dependencies.
Trail3DMagnitudeRange._BATCH_TYPE = Trail3DMagnitudeRangeBatch  # type: ignore[assignment]
