# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/trail3d_color.fbs".

# You can extend this class by creating a "Trail3DColorExt" class in "trail3d_color_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["Trail3DColor", "Trail3DColorBatch"]


class Trail3DColor(datatypes.Trail3DColor, ComponentMixin):
    """
    **Component**: How a [`archetypes.Trail3D`][rerun.archetypes.Trail3D] chooses its color.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of Trail3DColorExt in trail3d_color_ext.py

    # Note: there are no fields here because Trail3DColor delegates to datatypes.Trail3DColor


class Trail3DColorBatch(datatypes.Trail3DColorBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.Trail3DColor"


# This is patched in late to avoid circular dependencies.
Trail3DColor._BATCH_TYPE = Trail3DColorBatch  # type: ignore[assignment]
