# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/quad3d_thetas.fbs".

# You can extend this class by creating a "Quad3DThetasExt" class in "quad3d_thetas_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pyarrow as pa
from attrs import define, field

from .. import datatypes
from .._baseclasses import (
    BaseBatch,
)

__all__ = ["Quad3DThetas", "Quad3DThetasArrayLike", "Quad3DThetasBatch", "Quad3DThetasLike"]


def _quad3d_thetas__fl__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


def _quad3d_thetas__fr__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


def _quad3d_thetas__rl__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


def _quad3d_thetas__rr__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


@define(init=False)
class Quad3DThetas:
    """
    **Datatype**: Quadrotor actuator angles in radians.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(
        self: Any,
        *,
        fl: datatypes.Float32Like,
        fr: datatypes.Float32Like,
        rl: datatypes.Float32Like,
        rr: datatypes.Float32Like,
    ) -> None:
        """
        Create a new instance of the Quad3DThetas datatype.

        Parameters
        ----------
        fl:
            Front-left actuator angle.
        fr:
            Front-right actuator angle.
        rl:
            Rear-left actuator angle.
        rr:
            Rear-right actuator angle.

        """

        # You can define your own __init__ function as a member of Quad3DThetasExt in quad3d_thetas_ext.py
        self.__attrs_init__(fl=fl, fr=fr, rl=rl, rr=rr)

    fl: datatypes.Float32 = field(converter=_quad3d_thetas__fl__special_field_converter_override)
    # Front-left actuator angle.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    fr: datatypes.Float32 = field(converter=_quad3d_thetas__fr__special_field_converter_override)
    # Front-right actuator angle.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    rl: datatypes.Float32 = field(converter=_quad3d_thetas__rl__special_field_converter_override)
    # Rear-left actuator angle.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    rr: datatypes.Float32 = field(converter=_quad3d_thetas__rr__special_field_converter_override)
    # Rear-right actuator angle.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


Quad3DThetasLike = Quad3DThetas
"""A type alias for any Quad3DThetas-like object."""

Quad3DThetasArrayLike = Quad3DThetas | Sequence[Quad3DThetasLike]
"""A type alias for any Quad3DThetas-like array object."""


class Quad3DThetasBatch(BaseBatch[Quad3DThetasArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("fl", pa.float32(), nullable=False, metadata={}),
        pa.field("fr", pa.float32(), nullable=False, metadata={}),
        pa.field("rl", pa.float32(), nullable=False, metadata={}),
        pa.field("rr", pa.float32(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: Quad3DThetasArrayLike, data_type: pa.DataType) -> pa.Array:
        from rerun.datatypes import Float32Batch

        typed_data: Sequence[Quad3DThetas]

        if isinstance(data, Quad3DThetas):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                Float32Batch([x.fl for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                Float32Batch([x.fr for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                Float32Batch([x.rl for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                Float32Batch([x.rr for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
            ],
            fields=list(data_type),
        )
