# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_color.fbs".

# You can extend this class by creating a "Trail3DColorExt" class in "trail3d_color_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["Trail3DColor", "Trail3DColorArrayLike", "Trail3DColorBatch", "Trail3DColorLike"]


@define(init=False)
class Trail3DColor:
    """
    **Datatype**: Color selection for a [`archetypes.Trail3D`][rerun.archetypes.Trail3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, *, mode: int, color: int, colormap: int) -> None:
        """
        Create a new instance of the Trail3DColor datatype.

        Parameters
        ----------
        mode:
            Color mode. 1 means solid, 2 means magnitude colormap.
        color:
            Solid color used when mode is solid, packed as 0xRRGGBBAA.
        colormap:
            Colormap integer used when mode is magnitude.

        """

        # You can define your own __init__ function as a member of Trail3DColorExt in trail3d_color_ext.py
        self.__attrs_init__(mode=mode, color=color, colormap=colormap)

    mode: int = field(converter=int)
    # Color mode. 1 means solid, 2 means magnitude colormap.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    color: int = field(converter=int)
    # Solid color used when mode is solid, packed as 0xRRGGBBAA.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    colormap: int = field(converter=int)
    # Colormap integer used when mode is magnitude.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


Trail3DColorLike = Trail3DColor
"""A type alias for any Trail3DColor-like object."""

Trail3DColorArrayLike = Trail3DColor | Sequence[Trail3DColorLike]
"""A type alias for any Trail3DColor-like array object."""


class Trail3DColorBatch(BaseBatch[Trail3DColorArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("mode", pa.uint8(), nullable=False, metadata={}),
        pa.field("color", pa.uint32(), nullable=False, metadata={}),
        pa.field("colormap", pa.uint8(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: Trail3DColorArrayLike, data_type: pa.DataType) -> pa.Array:

        typed_data: Sequence[Trail3DColor]

        if isinstance(data, Trail3DColor):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                pa.array(np.asarray([x.mode for x in typed_data], dtype=np.uint8)),
                pa.array(np.asarray([x.color for x in typed_data], dtype=np.uint32)),
                pa.array(np.asarray([x.colormap for x in typed_data], dtype=np.uint8)),
            ],
            fields=list(data_type),
        )
