# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_point.fbs".

# You can extend this class by creating a "Trail3DPointExt" class in "trail3d_point_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pyarrow as pa
from attrs import define, field

from .. import datatypes
from .._baseclasses import (
    BaseBatch,
)

__all__ = ["Trail3DPoint", "Trail3DPointArrayLike", "Trail3DPointBatch", "Trail3DPointLike"]


def _trail3d_point__x__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


def _trail3d_point__y__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


def _trail3d_point__z__special_field_converter_override(x: datatypes.Float32Like) -> datatypes.Float32:
    if isinstance(x, datatypes.Float32):
        return x
    else:
        return datatypes.Float32(x)


@define(init=False)
class Trail3DPoint:
    """
    **Datatype**: A point in 3D space used by [`archetypes.Trail3D`][rerun.archetypes.Trail3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, *, x: datatypes.Float32Like, y: datatypes.Float32Like, z: datatypes.Float32Like) -> None:
        """
        Create a new instance of the Trail3DPoint datatype.

        Parameters
        ----------
        x:
            X coordinate.
        y:
            Y coordinate.
        z:
            Z coordinate.

        """

        # You can define your own __init__ function as a member of Trail3DPointExt in trail3d_point_ext.py
        self.__attrs_init__(x=x, y=y, z=z)

    x: datatypes.Float32 = field(converter=_trail3d_point__x__special_field_converter_override)
    # X coordinate.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    y: datatypes.Float32 = field(converter=_trail3d_point__y__special_field_converter_override)
    # Y coordinate.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    z: datatypes.Float32 = field(converter=_trail3d_point__z__special_field_converter_override)
    # Z coordinate.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


Trail3DPointLike = Trail3DPoint
"""A type alias for any Trail3DPoint-like object."""

Trail3DPointArrayLike = Trail3DPoint | Sequence[Trail3DPointLike]
"""A type alias for any Trail3DPoint-like array object."""


class Trail3DPointBatch(BaseBatch[Trail3DPointArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("x", pa.float32(), nullable=False, metadata={}),
        pa.field("y", pa.float32(), nullable=False, metadata={}),
        pa.field("z", pa.float32(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: Trail3DPointArrayLike, data_type: pa.DataType) -> pa.Array:
        from rerun.datatypes import Float32Batch

        typed_data: Sequence[Trail3DPoint]

        if isinstance(data, Trail3DPoint):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                Float32Batch([x.x for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                Float32Batch([x.y for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                Float32Batch([x.z for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
            ],
            fields=list(data_type),
        )
