# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_magnitude_range.fbs".

# You can extend this class by creating a "Trail3DMagnitudeRangeExt" class in "trail3d_magnitude_range_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)

__all__ = [
    "Trail3DMagnitudeRange",
    "Trail3DMagnitudeRangeArrayLike",
    "Trail3DMagnitudeRangeBatch",
    "Trail3DMagnitudeRangeLike",
]


@define(init=False)
class Trail3DMagnitudeRange:
    """
    **Datatype**: Magnitude range selection for a [`archetypes.Trail3D`][rerun.archetypes.Trail3D].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, *, mode: int, min: float, max: float) -> None:
        """
        Create a new instance of the Trail3DMagnitudeRange datatype.

        Parameters
        ----------
        mode:
            1 means auto, 2 means fixed.
        min:
            Fixed range minimum.
        max:
            Fixed range maximum.

        """

        # You can define your own __init__ function as a member of Trail3DMagnitudeRangeExt in trail3d_magnitude_range_ext.py
        self.__attrs_init__(mode=mode, min=min, max=max)

    mode: int = field(converter=int)
    # 1 means auto, 2 means fixed.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    min: float = field(converter=float)
    # Fixed range minimum.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    max: float = field(converter=float)
    # Fixed range maximum.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


Trail3DMagnitudeRangeLike = Trail3DMagnitudeRange
"""A type alias for any Trail3DMagnitudeRange-like object."""

Trail3DMagnitudeRangeArrayLike = Trail3DMagnitudeRange | Sequence[Trail3DMagnitudeRangeLike]
"""A type alias for any Trail3DMagnitudeRange-like array object."""


class Trail3DMagnitudeRangeBatch(BaseBatch[Trail3DMagnitudeRangeArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("mode", pa.uint8(), nullable=False, metadata={}),
        pa.field("min", pa.float64(), nullable=False, metadata={}),
        pa.field("max", pa.float64(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: Trail3DMagnitudeRangeArrayLike, data_type: pa.DataType) -> pa.Array:

        typed_data: Sequence[Trail3DMagnitudeRange]

        if isinstance(data, Trail3DMagnitudeRange):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                pa.array(np.asarray([x.mode for x in typed_data], dtype=np.uint8)),
                pa.array(np.asarray([x.min for x in typed_data], dtype=np.float64)),
                pa.array(np.asarray([x.max for x in typed_data], dtype=np.float64)),
            ],
            fields=list(data_type),
        )
