# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_length.fbs".

# You can extend this class by creating a "Trail3DLengthExt" class in "trail3d_length_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["Trail3DLength", "Trail3DLengthArrayLike", "Trail3DLengthBatch", "Trail3DLengthLike"]


@define(init=False)
class Trail3DLength:
    """
    **Datatype**: Trail length for temporal and sequence timelines.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, seconds: float, ticks: int) -> None:
        """
        Create a new instance of the Trail3DLength datatype.

        Parameters
        ----------
        seconds:
            Duration in seconds used on temporal timelines.
        ticks:
            Number of ticks used on sequence timelines.

        """

        # You can define your own __init__ function as a member of Trail3DLengthExt in trail3d_length_ext.py
        self.__attrs_init__(seconds=seconds, ticks=ticks)

    seconds: float = field(converter=float)
    # Duration in seconds used on temporal timelines.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    ticks: int = field(converter=int)
    # Number of ticks used on sequence timelines.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


Trail3DLengthLike = Trail3DLength
"""A type alias for any Trail3DLength-like object."""

Trail3DLengthArrayLike = Trail3DLength | Sequence[Trail3DLengthLike]
"""A type alias for any Trail3DLength-like array object."""


class Trail3DLengthBatch(BaseBatch[Trail3DLengthArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("seconds", pa.float64(), nullable=False, metadata={}),
        pa.field("ticks", pa.uint64(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: Trail3DLengthArrayLike, data_type: pa.DataType) -> pa.Array:

        typed_data: Sequence[Trail3DLength]

        if isinstance(data, Trail3DLength):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                pa.array(np.asarray([x.seconds for x in typed_data], dtype=np.float64)),
                pa.array(np.asarray([x.ticks for x in typed_data], dtype=np.uint64)),
            ],
            fields=list(data_type),
        )
