# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/quad3d.fbs".

# You can extend this class by creating a "Quad3DExt" class in "quad3d_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["Quad3D"]


@define(str=False, repr=False, init=False)
class Quad3D(Archetype, VisualizableArchetype):
    """
    **Archetype**: A quadrotor model rendered from local GLB assets.

    The public Rust API logs quadrotor transforms through normal
    [`archetypes.Transform3D`][rerun.archetypes.Transform3D] translation/quaternion components.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.Quad3D"

    def __init__(
        self: Any,
        thetas: datatypes.Quad3DThetasLike,
        *,
        model: datatypes.Utf8Like | None = None,
        label: datatypes.Utf8Like | None = None,
        show_label: datatypes.BoolLike | None = None,
    ) -> None:
        """
        Create a new instance of the Quad3D archetype.

        Parameters
        ----------
        thetas:
            Quadrotor actuator angles in radians.
        model:
            The GLB model filename.
        label:
            Optional text label for the quadrotor.
        show_label:
            Whether the text label should be shown.

        """

        # You can define your own __init__ function as a member of Quad3DExt in quad3d_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(thetas=thetas, model=model, label=label, show_label=show_label)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            thetas=None,
            model=None,
            label=None,
            show_label=None,
        )

    @classmethod
    def _clear(cls) -> Quad3D:
        """Produce an empty Quad3D, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        thetas: datatypes.Quad3DThetasLike | None = None,
        model: datatypes.Utf8Like | None = None,
        label: datatypes.Utf8Like | None = None,
        show_label: datatypes.BoolLike | None = None,
    ) -> Quad3D:
        """
        Update only some specific fields of a `Quad3D`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        thetas:
            Quadrotor actuator angles in radians.
        model:
            The GLB model filename.
        label:
            Optional text label for the quadrotor.
        show_label:
            Whether the text label should be shown.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "thetas": thetas,
                "model": model,
                "label": label,
                "show_label": show_label,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> Quad3D:
        """Clear all the fields of a `Quad3D`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_thetas() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Quad3D:thetas",
            archetype=Quad3D.NAME,
            component_type=components.Quad3DThetasBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_model() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Quad3D:model",
            archetype=Quad3D.NAME,
            component_type=components.Quad3DModelBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_label() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Quad3D:label",
            archetype=Quad3D.NAME,
            component_type=components.TextBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_show_label() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Quad3D:show_label",
            archetype=Quad3D.NAME,
            component_type=components.ShowLabelsBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        thetas: datatypes.Quad3DThetasArrayLike | None = None,
        model: datatypes.Utf8ArrayLike | None = None,
        label: datatypes.Utf8ArrayLike | None = None,
        show_label: datatypes.BoolArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        thetas:
            Quadrotor actuator angles in radians.
        model:
            The GLB model filename.
        label:
            Optional text label for the quadrotor.
        show_label:
            Whether the text label should be shown.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                thetas=thetas,
                model=model,
                label=label,
                show_label=show_label,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "Quad3D:thetas": thetas,
            "Quad3D:model": model,
            "Quad3D:label": label,
            "Quad3D:show_label": show_label,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    thetas: components.Quad3DThetasBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Quad3DThetasBatch._converter,  # type: ignore[misc]
    )
    # Quadrotor actuator angles in radians.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    model: components.Quad3DModelBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Quad3DModelBatch._converter,  # type: ignore[misc]
    )
    # The GLB model filename.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    label: components.TextBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TextBatch._converter,  # type: ignore[misc]
    )
    # Optional text label for the quadrotor.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    show_label: components.ShowLabelsBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ShowLabelsBatch._converter,  # type: ignore[misc]
    )
    # Whether the text label should be shown.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("Quad3D", overrides=self.as_component_batches(), mappings=mappings)
