# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/trail3d.fbs".

# You can extend this class by creating a "Trail3DExt" class in "trail3d_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["Trail3D"]


@define(str=False, repr=False, init=False)
class Trail3D(Archetype, VisualizableArchetype):
    """
    **Archetype**: A time-windowed 3D trail built from logged points.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.Trail3D"

    def __init__(
        self: Any,
        point: datatypes.Trail3DPointLike,
        *,
        color: datatypes.Trail3DColorLike | None = None,
        radius: datatypes.Float32Like | None = None,
        length: datatypes.Trail3DLengthLike | None = None,
        magnitude: datatypes.Float64Like | None = None,
        magnitude_range: datatypes.Trail3DMagnitudeRangeLike | None = None,
    ) -> None:
        """
        Create a new instance of the Trail3D archetype.

        Parameters
        ----------
        point:
            A 3D point appended to the trail.
        color:
            How the trail color is chosen.
        radius:
            The rendered trail line radius.
        length:
            Trail length for temporal and sequence timelines.
        magnitude:
            Optional scalar used to color the trail.
        magnitude_range:
            How the magnitude range is chosen.

        """

        # You can define your own __init__ function as a member of Trail3DExt in trail3d_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                point=point,
                color=color,
                radius=radius,
                length=length,
                magnitude=magnitude,
                magnitude_range=magnitude_range,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            point=None,
            color=None,
            radius=None,
            length=None,
            magnitude=None,
            magnitude_range=None,
        )

    @classmethod
    def _clear(cls) -> Trail3D:
        """Produce an empty Trail3D, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        point: datatypes.Trail3DPointLike | None = None,
        color: datatypes.Trail3DColorLike | None = None,
        radius: datatypes.Float32Like | None = None,
        length: datatypes.Trail3DLengthLike | None = None,
        magnitude: datatypes.Float64Like | None = None,
        magnitude_range: datatypes.Trail3DMagnitudeRangeLike | None = None,
    ) -> Trail3D:
        """
        Update only some specific fields of a `Trail3D`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        point:
            A 3D point appended to the trail.
        color:
            How the trail color is chosen.
        radius:
            The rendered trail line radius.
        length:
            Trail length for temporal and sequence timelines.
        magnitude:
            Optional scalar used to color the trail.
        magnitude_range:
            How the magnitude range is chosen.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "point": point,
                "color": color,
                "radius": radius,
                "length": length,
                "magnitude": magnitude,
                "magnitude_range": magnitude_range,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> Trail3D:
        """Clear all the fields of a `Trail3D`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_point() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:point",
            archetype=Trail3D.NAME,
            component_type=components.Trail3DPointBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_color() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:color",
            archetype=Trail3D.NAME,
            component_type=components.Trail3DColorBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_radius() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:radius",
            archetype=Trail3D.NAME,
            component_type=components.RadiusBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_length() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:length",
            archetype=Trail3D.NAME,
            component_type=components.Trail3DLengthBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_magnitude() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:magnitude",
            archetype=Trail3D.NAME,
            component_type=components.Trail3DMagnitudeBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_magnitude_range() -> ComponentDescriptor:
        return ComponentDescriptor(
            "Trail3D:magnitude_range",
            archetype=Trail3D.NAME,
            component_type=components.Trail3DMagnitudeRangeBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        point: datatypes.Trail3DPointArrayLike | None = None,
        color: datatypes.Trail3DColorArrayLike | None = None,
        radius: datatypes.Float32ArrayLike | None = None,
        length: datatypes.Trail3DLengthArrayLike | None = None,
        magnitude: datatypes.Float64ArrayLike | None = None,
        magnitude_range: datatypes.Trail3DMagnitudeRangeArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        point:
            A 3D point appended to the trail.
        color:
            How the trail color is chosen.
        radius:
            The rendered trail line radius.
        length:
            Trail length for temporal and sequence timelines.
        magnitude:
            Optional scalar used to color the trail.
        magnitude_range:
            How the magnitude range is chosen.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                point=point,
                color=color,
                radius=radius,
                length=length,
                magnitude=magnitude,
                magnitude_range=magnitude_range,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "Trail3D:point": point,
            "Trail3D:color": color,
            "Trail3D:radius": radius,
            "Trail3D:length": length,
            "Trail3D:magnitude": magnitude,
            "Trail3D:magnitude_range": magnitude_range,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    point: components.Trail3DPointBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Trail3DPointBatch._converter,  # type: ignore[misc]
    )
    # A 3D point appended to the trail.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    color: components.Trail3DColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Trail3DColorBatch._converter,  # type: ignore[misc]
    )
    # How the trail color is chosen.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    radius: components.RadiusBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.RadiusBatch._converter,  # type: ignore[misc]
    )
    # The rendered trail line radius.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    length: components.Trail3DLengthBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Trail3DLengthBatch._converter,  # type: ignore[misc]
    )
    # Trail length for temporal and sequence timelines.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    magnitude: components.Trail3DMagnitudeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Trail3DMagnitudeBatch._converter,  # type: ignore[misc]
    )
    # Optional scalar used to color the trail.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    magnitude_range: components.Trail3DMagnitudeRangeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Trail3DMagnitudeRangeBatch._converter,  # type: ignore[misc]
    )
    # How the magnitude range is chosen.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("Trail3D", overrides=self.as_component_batches(), mappings=mappings)
