// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/quad3d.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A quadrotor model rendered from local GLB assets.
///
/// The public Rust API logs quadrotor transforms through normal
/// [`archetypes::Transform3D`][crate::archetypes::Transform3D] translation/quaternion components.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Quad3D {
    /// Quadrotor actuator angles in radians.
    pub thetas: Option<SerializedComponentBatch>,

    /// The GLB model filename.
    pub model: Option<SerializedComponentBatch>,

    /// Optional text label for the quadrotor.
    pub label: Option<SerializedComponentBatch>,

    /// Whether the text label should be shown.
    pub show_label: Option<SerializedComponentBatch>,
}

impl Quad3D {
    /// Returns the [`ComponentDescriptor`] for [`Self::thetas`].
    ///
    /// The corresponding component is [`crate::components::Quad3DThetas`].
    #[inline]
    pub fn descriptor_thetas() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Quad3D".into()),
            component: "Quad3D:thetas".into(),
            component_type: Some("rerun.components.Quad3DThetas".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::model`].
    ///
    /// The corresponding component is [`crate::components::Quad3DModel`].
    #[inline]
    pub fn descriptor_model() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Quad3D".into()),
            component: "Quad3D:model".into(),
            component_type: Some("rerun.components.Quad3DModel".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::label`].
    ///
    /// The corresponding component is [`crate::components::Text`].
    #[inline]
    pub fn descriptor_label() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Quad3D".into()),
            component: "Quad3D:label".into(),
            component_type: Some("rerun.components.Text".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::show_label`].
    ///
    /// The corresponding component is [`crate::components::ShowLabels`].
    #[inline]
    pub fn descriptor_show_label() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Quad3D".into()),
            component: "Quad3D:show_label".into(),
            component_type: Some("rerun.components.ShowLabels".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [Quad3D::descriptor_thetas()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [Quad3D::descriptor_model()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| [Quad3D::descriptor_label(), Quad3D::descriptor_show_label()]);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            Quad3D::descriptor_thetas(),
            Quad3D::descriptor_model(),
            Quad3D::descriptor_label(),
            Quad3D::descriptor_show_label(),
        ]
    });

impl Quad3D {
    /// The total number of components in the archetype: 1 required, 1 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 4usize;
}

impl ::re_types_core::Archetype for Quad3D {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.Quad3D".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Quad 3D"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let thetas = arrays_by_descr
            .get(&Self::descriptor_thetas())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_thetas()));
        let model = arrays_by_descr
            .get(&Self::descriptor_model())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_model()));
        let label = arrays_by_descr
            .get(&Self::descriptor_label())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_label()));
        let show_label = arrays_by_descr
            .get(&Self::descriptor_show_label())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_show_label())
            });
        Ok(Self {
            thetas,
            model,
            label,
            show_label,
        })
    }
}

impl ::re_types_core::AsComponents for Quad3D {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.thetas.clone(),
            self.model.clone(),
            self.label.clone(),
            self.show_label.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for Quad3D {}

impl crate::VisualizableArchetype for Quad3D {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("Quad3D").with_overrides(self)
    }
}

impl Quad3D {
    /// Create a new `Quad3D`.
    #[inline]
    pub(crate) fn new(thetas: impl Into<crate::components::Quad3DThetas>) -> Self {
        Self {
            thetas: try_serialize_field(Self::descriptor_thetas(), [thetas]),
            model: None,
            label: None,
            show_label: None,
        }
    }

    /// Update only some specific fields of a `Quad3D`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `Quad3D`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            thetas: Some(SerializedComponentBatch::new(
                crate::components::Quad3DThetas::arrow_empty(),
                Self::descriptor_thetas(),
            )),
            model: Some(SerializedComponentBatch::new(
                crate::components::Quad3DModel::arrow_empty(),
                Self::descriptor_model(),
            )),
            label: Some(SerializedComponentBatch::new(
                crate::components::Text::arrow_empty(),
                Self::descriptor_label(),
            )),
            show_label: Some(SerializedComponentBatch::new(
                crate::components::ShowLabels::arrow_empty(),
                Self::descriptor_show_label(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.thetas
                .map(|thetas| thetas.partitioned(_lengths.clone()))
                .transpose()?,
            self.model
                .map(|model| model.partitioned(_lengths.clone()))
                .transpose()?,
            self.label
                .map(|label| label.partitioned(_lengths.clone()))
                .transpose()?,
            self.show_label
                .map(|show_label| show_label.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_thetas = self.thetas.as_ref().map(|b| b.array.len());
        let len_model = self.model.as_ref().map(|b| b.array.len());
        let len_label = self.label.as_ref().map(|b| b.array.len());
        let len_show_label = self.show_label.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_thetas)
            .or(len_model)
            .or(len_label)
            .or(len_show_label)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Quadrotor actuator angles in radians.
    #[inline]
    pub fn with_thetas(mut self, thetas: impl Into<crate::components::Quad3DThetas>) -> Self {
        self.thetas = try_serialize_field(Self::descriptor_thetas(), [thetas]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Quad3DThetas`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_thetas`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_thetas(
        mut self,
        thetas: impl IntoIterator<Item = impl Into<crate::components::Quad3DThetas>>,
    ) -> Self {
        self.thetas = try_serialize_field(Self::descriptor_thetas(), thetas);
        self
    }

    /// The GLB model filename.
    #[inline]
    pub fn with_model(mut self, model: impl Into<crate::components::Quad3DModel>) -> Self {
        self.model = try_serialize_field(Self::descriptor_model(), [model]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Quad3DModel`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_model`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_model(
        mut self,
        model: impl IntoIterator<Item = impl Into<crate::components::Quad3DModel>>,
    ) -> Self {
        self.model = try_serialize_field(Self::descriptor_model(), model);
        self
    }

    /// Optional text label for the quadrotor.
    #[inline]
    pub fn with_label(mut self, label: impl Into<crate::components::Text>) -> Self {
        self.label = try_serialize_field(Self::descriptor_label(), [label]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Text`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_label`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_label(
        mut self,
        label: impl IntoIterator<Item = impl Into<crate::components::Text>>,
    ) -> Self {
        self.label = try_serialize_field(Self::descriptor_label(), label);
        self
    }

    /// Whether the text label should be shown.
    #[inline]
    pub fn with_show_label(mut self, show_label: impl Into<crate::components::ShowLabels>) -> Self {
        self.show_label = try_serialize_field(Self::descriptor_show_label(), [show_label]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ShowLabels`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_show_label`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_show_label(
        mut self,
        show_label: impl IntoIterator<Item = impl Into<crate::components::ShowLabels>>,
    ) -> Self {
        self.show_label = try_serialize_field(Self::descriptor_show_label(), show_label);
        self
    }
}

impl ::re_byte_size::SizeBytes for Quad3D {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.thetas.heap_size_bytes()
            + self.model.heap_size_bytes()
            + self.label.heap_size_bytes()
            + self.show_label.heap_size_bytes()
    }
}
