// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/trail3d.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A time-windowed 3D trail built from logged points.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Trail3D {
    /// A 3D point appended to the trail.
    pub point: Option<SerializedComponentBatch>,

    /// How the trail color is chosen.
    pub color: Option<SerializedComponentBatch>,

    /// The rendered trail line radius.
    pub radius: Option<SerializedComponentBatch>,

    /// Trail length for temporal and sequence timelines.
    pub length: Option<SerializedComponentBatch>,

    /// Optional scalar used to color the trail.
    pub magnitude: Option<SerializedComponentBatch>,

    /// How the magnitude range is chosen.
    pub magnitude_range: Option<SerializedComponentBatch>,
}

impl Trail3D {
    /// Returns the [`ComponentDescriptor`] for [`Self::point`].
    ///
    /// The corresponding component is [`crate::components::Trail3DPoint`].
    #[inline]
    pub fn descriptor_point() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:point".into(),
            component_type: Some("rerun.components.Trail3DPoint".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::color`].
    ///
    /// The corresponding component is [`crate::components::Trail3DColor`].
    #[inline]
    pub fn descriptor_color() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:color".into(),
            component_type: Some("rerun.components.Trail3DColor".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::radius`].
    ///
    /// The corresponding component is [`crate::components::Radius`].
    #[inline]
    pub fn descriptor_radius() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:radius".into(),
            component_type: Some("rerun.components.Radius".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::length`].
    ///
    /// The corresponding component is [`crate::components::Trail3DLength`].
    #[inline]
    pub fn descriptor_length() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:length".into(),
            component_type: Some("rerun.components.Trail3DLength".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::magnitude`].
    ///
    /// The corresponding component is [`crate::components::Trail3DMagnitude`].
    #[inline]
    pub fn descriptor_magnitude() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:magnitude".into(),
            component_type: Some("rerun.components.Trail3DMagnitude".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::magnitude_range`].
    ///
    /// The corresponding component is [`crate::components::Trail3DMagnitudeRange`].
    #[inline]
    pub fn descriptor_magnitude_range() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Trail3D".into()),
            component: "Trail3D:magnitude_range".into(),
            component_type: Some("rerun.components.Trail3DMagnitudeRange".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [Trail3D::descriptor_point()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            Trail3D::descriptor_color(),
            Trail3D::descriptor_radius(),
            Trail3D::descriptor_length(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            Trail3D::descriptor_magnitude(),
            Trail3D::descriptor_magnitude_range(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            Trail3D::descriptor_point(),
            Trail3D::descriptor_color(),
            Trail3D::descriptor_radius(),
            Trail3D::descriptor_length(),
            Trail3D::descriptor_magnitude(),
            Trail3D::descriptor_magnitude_range(),
        ]
    });

impl Trail3D {
    /// The total number of components in the archetype: 1 required, 3 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 6usize;
}

impl ::re_types_core::Archetype for Trail3D {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.Trail3D".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Trail 3D"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let point = arrays_by_descr
            .get(&Self::descriptor_point())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_point()));
        let color = arrays_by_descr
            .get(&Self::descriptor_color())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_color()));
        let radius = arrays_by_descr
            .get(&Self::descriptor_radius())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_radius()));
        let length = arrays_by_descr
            .get(&Self::descriptor_length())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_length()));
        let magnitude = arrays_by_descr
            .get(&Self::descriptor_magnitude())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_magnitude())
            });
        let magnitude_range = arrays_by_descr
            .get(&Self::descriptor_magnitude_range())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_magnitude_range())
            });
        Ok(Self {
            point,
            color,
            radius,
            length,
            magnitude,
            magnitude_range,
        })
    }
}

impl ::re_types_core::AsComponents for Trail3D {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.point.clone(),
            self.color.clone(),
            self.radius.clone(),
            self.length.clone(),
            self.magnitude.clone(),
            self.magnitude_range.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for Trail3D {}

impl crate::VisualizableArchetype for Trail3D {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("Trail3D").with_overrides(self)
    }
}

impl Trail3D {
    /// Create a new `Trail3D`.
    #[inline]
    pub(crate) fn new(point: impl Into<crate::components::Trail3DPoint>) -> Self {
        Self {
            point: try_serialize_field(Self::descriptor_point(), [point]),
            color: None,
            radius: None,
            length: None,
            magnitude: None,
            magnitude_range: None,
        }
    }

    /// Update only some specific fields of a `Trail3D`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `Trail3D`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            point: Some(SerializedComponentBatch::new(
                crate::components::Trail3DPoint::arrow_empty(),
                Self::descriptor_point(),
            )),
            color: Some(SerializedComponentBatch::new(
                crate::components::Trail3DColor::arrow_empty(),
                Self::descriptor_color(),
            )),
            radius: Some(SerializedComponentBatch::new(
                crate::components::Radius::arrow_empty(),
                Self::descriptor_radius(),
            )),
            length: Some(SerializedComponentBatch::new(
                crate::components::Trail3DLength::arrow_empty(),
                Self::descriptor_length(),
            )),
            magnitude: Some(SerializedComponentBatch::new(
                crate::components::Trail3DMagnitude::arrow_empty(),
                Self::descriptor_magnitude(),
            )),
            magnitude_range: Some(SerializedComponentBatch::new(
                crate::components::Trail3DMagnitudeRange::arrow_empty(),
                Self::descriptor_magnitude_range(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.point
                .map(|point| point.partitioned(_lengths.clone()))
                .transpose()?,
            self.color
                .map(|color| color.partitioned(_lengths.clone()))
                .transpose()?,
            self.radius
                .map(|radius| radius.partitioned(_lengths.clone()))
                .transpose()?,
            self.length
                .map(|length| length.partitioned(_lengths.clone()))
                .transpose()?,
            self.magnitude
                .map(|magnitude| magnitude.partitioned(_lengths.clone()))
                .transpose()?,
            self.magnitude_range
                .map(|magnitude_range| magnitude_range.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_point = self.point.as_ref().map(|b| b.array.len());
        let len_color = self.color.as_ref().map(|b| b.array.len());
        let len_radius = self.radius.as_ref().map(|b| b.array.len());
        let len_length = self.length.as_ref().map(|b| b.array.len());
        let len_magnitude = self.magnitude.as_ref().map(|b| b.array.len());
        let len_magnitude_range = self.magnitude_range.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_point)
            .or(len_color)
            .or(len_radius)
            .or(len_length)
            .or(len_magnitude)
            .or(len_magnitude_range)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// A 3D point appended to the trail.
    #[inline]
    pub fn with_point(mut self, point: impl Into<crate::components::Trail3DPoint>) -> Self {
        self.point = try_serialize_field(Self::descriptor_point(), [point]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Trail3DPoint`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_point`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_point(
        mut self,
        point: impl IntoIterator<Item = impl Into<crate::components::Trail3DPoint>>,
    ) -> Self {
        self.point = try_serialize_field(Self::descriptor_point(), point);
        self
    }

    /// How the trail color is chosen.
    #[inline]
    pub fn with_color(mut self, color: impl Into<crate::components::Trail3DColor>) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), [color]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Trail3DColor`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_color`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_color(
        mut self,
        color: impl IntoIterator<Item = impl Into<crate::components::Trail3DColor>>,
    ) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), color);
        self
    }

    /// The rendered trail line radius.
    #[inline]
    pub fn with_radius(mut self, radius: impl Into<crate::components::Radius>) -> Self {
        self.radius = try_serialize_field(Self::descriptor_radius(), [radius]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Radius`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_radius`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_radius(
        mut self,
        radius: impl IntoIterator<Item = impl Into<crate::components::Radius>>,
    ) -> Self {
        self.radius = try_serialize_field(Self::descriptor_radius(), radius);
        self
    }

    /// Trail length for temporal and sequence timelines.
    #[inline]
    pub fn with_length(mut self, length: impl Into<crate::components::Trail3DLength>) -> Self {
        self.length = try_serialize_field(Self::descriptor_length(), [length]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Trail3DLength`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_length`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_length(
        mut self,
        length: impl IntoIterator<Item = impl Into<crate::components::Trail3DLength>>,
    ) -> Self {
        self.length = try_serialize_field(Self::descriptor_length(), length);
        self
    }

    /// Optional scalar used to color the trail.
    #[inline]
    pub fn with_magnitude(
        mut self,
        magnitude: impl Into<crate::components::Trail3DMagnitude>,
    ) -> Self {
        self.magnitude = try_serialize_field(Self::descriptor_magnitude(), [magnitude]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Trail3DMagnitude`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_magnitude`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_magnitude(
        mut self,
        magnitude: impl IntoIterator<Item = impl Into<crate::components::Trail3DMagnitude>>,
    ) -> Self {
        self.magnitude = try_serialize_field(Self::descriptor_magnitude(), magnitude);
        self
    }

    /// How the magnitude range is chosen.
    #[inline]
    pub fn with_magnitude_range(
        mut self,
        magnitude_range: impl Into<crate::components::Trail3DMagnitudeRange>,
    ) -> Self {
        self.magnitude_range =
            try_serialize_field(Self::descriptor_magnitude_range(), [magnitude_range]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Trail3DMagnitudeRange`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_magnitude_range`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_magnitude_range(
        mut self,
        magnitude_range: impl IntoIterator<Item = impl Into<crate::components::Trail3DMagnitudeRange>>,
    ) -> Self {
        self.magnitude_range =
            try_serialize_field(Self::descriptor_magnitude_range(), magnitude_range);
        self
    }
}

impl ::re_byte_size::SizeBytes for Trail3D {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.point.heap_size_bytes()
            + self.color.heap_size_bytes()
            + self.radius.heap_size_bytes()
            + self.length.heap_size_bytes()
            + self.magnitude.heap_size_bytes()
            + self.magnitude_range.heap_size_bytes()
    }
}
