// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/quad3d_thetas.fbs".

#pragma once

#include "../result.hpp"
#include "float32.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: Quadrotor actuator angles in radians.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Quad3DThetas {
        /// Front-left actuator angle.
        rerun::datatypes::Float32 fl;

        /// Front-right actuator angle.
        rerun::datatypes::Float32 fr;

        /// Rear-left actuator angle.
        rerun::datatypes::Float32 rl;

        /// Rear-right actuator angle.
        rerun::datatypes::Float32 rr;

      public:
        Quad3DThetas() = default;
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Quad3DThetas> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.Quad3DThetas";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::Quad3DThetas` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Quad3DThetas* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::Quad3DThetas* elements,
            size_t num_elements
        );
    };
} // namespace rerun
