// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_color.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: Color selection for a `archetypes::Trail3D`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DColor {
        /// Color mode. 1 means solid, 2 means magnitude colormap.
        uint8_t mode;

        /// Solid color used when mode is solid, packed as 0xRRGGBBAA.
        uint32_t color;

        /// Colormap integer used when mode is magnitude.
        uint8_t colormap;

      public:
        Trail3DColor() = default;
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Trail3DColor> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.Trail3DColor";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::Trail3DColor` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Trail3DColor* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::Trail3DColor* elements,
            size_t num_elements
        );
    };
} // namespace rerun
