// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/trail3d_point.fbs".

#pragma once

#include "../result.hpp"
#include "float32.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: A point in 3D space used by `archetypes::Trail3D`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Trail3DPoint {
        /// X coordinate.
        rerun::datatypes::Float32 x;

        /// Y coordinate.
        rerun::datatypes::Float32 y;

        /// Z coordinate.
        rerun::datatypes::Float32 z;

      public:
        Trail3DPoint() = default;
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Trail3DPoint> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.Trail3DPoint";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::Trail3DPoint` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Trail3DPoint* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::Trail3DPoint* elements,
            size_t num_elements
        );
    };
} // namespace rerun
